# Let's test your knowledge about Python, data structures, NumPy, and pandas.
We are going to createa a dummy dataset for some Youtubers regarding their channals. We will create data including:
1.  Decide the size of the dataset by using a SIZE constant variable
1.  ChannelID (`Y0001`, `Y0002`, ...)
1.  Number of subscribers
1.  Number of videos
1.  Number of total views
1.  Category (`['music','news','gaming','food','travel']`)
1.  Language (`['English','Spanish','Japanese','Franch','Russia','Chinese']`)
1.  Type(`['Corperate','Goverment','NGO','Individual']`)


Then we will play with the dummy dataset with our knowledge of pandas, including:
1.  Access
1.  Sampling
1.  Filtering
1.  Aggregation
1.  Manipulation


## Setup environment
Let's import random, Numpy, and pandas

In [1]:
import random
import numpy as np
import pandas as pd

## Dummy dataset generation

### Setup SIZE

In [2]:
# We make this variable SIZE because it supposed to be constant for the runtime.
SIZE = 10000

### Generate ChannelID

In [3]:
ids = ['Y{0:04d}'.format(x) for x in range(SIZE)]
ids[:5], ids[-5:]

(['Y0000', 'Y0001', 'Y0002', 'Y0003', 'Y0004'],
 ['Y9995', 'Y9996', 'Y9997', 'Y9998', 'Y9999'])

### Generate # of subscribers

#### We first simulate a normal distribution

In [34]:
subs = np.random.normal(100000, 50000, (SIZE))
subs[:5], subs[-5:]

(array([ 25979.25625761,  72016.9928302 , -17051.07094428, 110656.35236934,
        118882.36196621]),
 array([ 57563.74865165, 110231.26803671, 113216.51265991,  94035.36265461,
         47998.57231864]))

#### We convert the float numbers to integer

In [35]:
subs = subs.astype(int)
subs[:5], subs[-5:]

(array([ 25979,  72016, -17051, 110656, 118882]),
 array([ 57563, 110231, 113216,  94035,  47998]))

#### We check if there are non-positive numbers of subscribers

In [36]:
subs[subs <= 0 ]

array([-17051,  -5158,  -5598, -32716, -12344,  -1099,  -8336, -16187,
       -57055, -10649, -23473, -33470,  -9121, -54695,  -3798, -26192,
       -27813,  -5614, -23558, -15796, -20841,  -7425, -70037, -22393,
        -2326, -17669, -11272, -10248, -23594, -18201, -17413, -47085,
       -29650,  -3606,  -1532,  -1435,  -4609, -21031,  -5038,  -7146,
       -15670, -49331, -10437, -10202, -47368, -37989, -14054, -31650,
         -352, -29737, -14918,  -3164, -15981, -29455, -23858,   -601,
       -21710, -16262,  -1858, -31764,  -2709, -31368, -18537, -23284,
         -647,  -7588, -59450,  -1477, -30715,  -1771,  -1207,  -1869,
        -4614, -35974,  -6139,  -6861, -10544,  -8006, -17779, -14469,
       -15931, -38581, -22359, -37964, -20527, -13129, -22942, -12377,
       -79150, -15518,   -711, -10351, -16462,  -4147,  -4049, -75636,
       -21061, -30426, -12530,   -972, -11931, -10909, -15112,  -9795,
       -22312, -36714,  -9142,  -2375, -22893,  -1035, -29517, -12414,
      

#### We set them to be 1

In [39]:
subs[subs <= 0 ] = 1
subs

array([ 25979,  72016,      1, ..., 113216,  94035,  47998])

### Generate number of videos


#### We use a uniform distribution this time (just for practice)

In [40]:
nvideos = [np.random.randint(1, 100) for i in range(SIZE)]
nvideos[:5], nvideos[-5:]

([33, 82, 16, 71, 50], [95, 57, 34, 24, 67])

### We simulate the number of views

#### To make it real, we will use the # of subscribers and # of videos as factors to get the # of total views

In [41]:
views = [ int(x*1.5*np.random.random() + y*2*np.random.random() + np.random.randint(-1000, 1000))
for x, y in zip(subs, nvideos)]
views[:5], views[-5:]

([25011, 69990, -775, 119443, 168311], [2954, 164929, 129475, 14145, 71057])

In [45]:
views = np.array(views)
views

array([ 25011,  69990,   -775, ..., 129475,  14145,  71057])

In [46]:
views[views < 0]

array([-775, -524, -597, -401, -205, -303, -352, -811, -716, -427,   -6,
       -520,  -95, -817, -151, -761,  -37, -732, -866, -549, -460, -930,
       -263, -471, -451, -951, -458, -619, -356,  -14, -244, -865, -452,
       -103, -367, -917, -144, -791,  -76, -119, -881, -501, -501, -922,
        -37, -177, -709,  -19, -836, -100, -889,  -43, -702, -829,  -37,
       -721, -128, -322, -251, -269, -348, -186, -407, -592, -805, -277,
       -787, -741,  -41, -502, -333, -111,  -77, -722, -471, -691, -555,
       -367, -905, -343, -948, -794, -491, -546, -503, -521, -792, -297,
        -76, -445, -551, -326, -569, -181, -105, -249, -240,  -70, -781,
       -936, -156, -359, -578,   -9, -424, -536, -768, -525, -518, -694,
       -244, -412, -317, -538, -438, -258, -237, -733, -218, -545, -307,
       -357, -363, -633, -840,  -23, -268, -543, -349, -572, -157, -167,
       -307, -305, -453, -410,  -92, -197, -480, -222])

In [47]:
views[views < 0] = 0
views[views < 0]

array([], dtype=int64)

### Category

>Category (`['music','news','gaming','food','travel']`)

In [48]:
category = np.random.choice(['music','news','gaming','food','travel'], SIZE)
category[:20]

array(['news', 'gaming', 'music', 'news', 'travel', 'food', 'music',
       'news', 'food', 'gaming', 'gaming', 'news', 'news', 'travel',
       'news', 'food', 'travel', 'music', 'travel', 'music'], dtype='<U6')

### Language
>Language (`['English','Spanish','Japanese','Franch','Russia','Chinese']`)


In [49]:
language = np.random.choice(['English','Spanish','Japanese','Franch','Russia','Chinese'],
                            SIZE, p=[0.5, 0.1, 0.1, 0.1, 0.1, 0.1])
language[:20]

array(['English', 'English', 'English', 'Chinese', 'Japanese', 'English',
       'Chinese', 'English', 'Chinese', 'English', 'English', 'Chinese',
       'Franch', 'English', 'English', 'Spanish', 'Russia', 'Russia',
       'Chinese', 'English'], dtype='<U8')

### Type
>Type(`['Corperate','Goverment','NGO','Individual']`)

In [50]:
tp = np.random.choice(['Corperate','Goverment','NGO','Individual'], SIZE, p=[0.1, 0.2, 0.3, 0.4])
tp[:20]

array(['NGO', 'NGO', 'Individual', 'Individual', 'NGO', 'Goverment',
       'Goverment', 'Individual', 'Individual', 'Individual',
       'Individual', 'Corperate', 'Individual', 'Individual', 'NGO',
       'Individual', 'Corperate', 'Corperate', 'Goverment', 'Individual'],
      dtype='<U10')

### Now we have all attributes, let's put them into a dataframe

In [51]:
df = pd.DataFrame({'ChannelID': ids,
                   'subs': subs,
                   'nvideos': nvideos,
                   'views': views,
                   'Category': category,
                   'Language':language,
                   'Type': tp},
                  index = ids)
df.head()

ChannelID    subs  nvideos   views Category  Language        Type
Y0000     Y0000   25979       33   25011     news   English         NGO
Y0001     Y0001   72016       82   69990   gaming   English         NGO
Y0002     Y0002       1       16       0    music   English  Individual
Y0003     Y0003  110656       71  119443     news   Chinese  Individual
Y0004     Y0004  118882       50  168311   travel  Japanese         NGO

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, Y0000 to Y9999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ChannelID  10000 non-null  object
 1   subs       10000 non-null  int64 
 2   nvideos    10000 non-null  int64 
 3   views      10000 non-null  int64 
 4   Category   10000 non-null  object
 5   Language   10000 non-null  object
 6   Type       10000 non-null  object
dtypes: int64(3), object(4)
memory usage: 625.0+ KB


### Let's save the dummy dataset to `youtube_channels.csv`

In [55]:
df.to_csv('youtube_channels.csv', index=True)

## Let's play with the dataframe a little bit

### Sampling

#### Select certain rows

In [19]:
df_sub1 = df.loc[:'Y0100']
df_sub1

ChannelID    subs  nvideos   views Category Language        Type
Y0000     Y0000   28045       61   34515     food   Russia  Individual
Y0001     Y0001  112407        8  137830     food  English   Goverment
Y0002     Y0002   75610       89   75561     food   Franch   Goverment
Y0003     Y0003   68566       17   14567     food  English  Individual
Y0004     Y0004  154427       92  172224   gaming  English         NGO
...         ...     ...      ...     ...      ...      ...         ...
Y0096     Y0096   72594       18    8188     news   Franch  Individual
Y0097     Y0097  125410       90  152805   travel  English  Individual
Y0098     Y0098  137602       73     676    music  English  Individual
Y0099     Y0099  119988       34   52080     news  English         NGO
Y0100     Y0100  105222       19   69281   gaming  English  Individual

[101 rows x 7 columns]

#### Select certain rows and columns

In [20]:
df_sub2 = df.loc[:'Y1000', ['subs','views']]
df_sub2

subs   views
Y0000   28045   34515
Y0001  112407  137830
Y0002   75610   75561
Y0003   68566   14567
Y0004  154427  172224
...       ...     ...
Y0996   35571   51580
Y0997  102212   95143
Y0998   49603   63737
Y0999    8028    2545
Y1000  131758  106912

[1001 rows x 2 columns]

#### Select randome rows

In [21]:
df_sub3 = df.iloc[random.sample(range(0, SIZE), 100)]
df_sub3

ChannelID    subs  nvideos   views Category  Language        Type
Y7934     Y7934       1       58     479     news   English         NGO
Y4974     Y4974   48515       47   25066     food    Russia         NGO
Y8898     Y8898   99912       73    1385     food    Russia  Individual
Y1580     Y1580   37341       13   34180   gaming   Chinese   Goverment
Y4149     Y4149  173878       19  226348    music  Japanese         NGO
...         ...     ...      ...     ...      ...       ...         ...
Y8747     Y8747  101132       80  150711     news    Russia  Individual
Y6329     Y6329  114735       80  170020     food   English  Individual
Y0242     Y0242  178802       55  220842     news    Russia  Individual
Y2615     Y2615  219678        1  254137    music   English   Corperate
Y2270     Y2270   84831       39  102813    music   English  Individual

[100 rows x 7 columns]

#### Select random rows with selected columns

In [22]:
df_sub4 = df.iloc[random.sample(range(0, SIZE), 100)][['subs','views']]
df_sub4

subs   views
Y7633   79223   40161
Y7965   77167   40551
Y4786   28367   35095
Y1991  179690  176777
Y1831   41955    4277
...       ...     ...
Y8427   93260    4679
Y6860  185962  266192
Y1589  166517   67476
Y3098   64708    2307
Y4297   90637   55938

[100 rows x 2 columns]

### Filtering

#### Super Popular Channel

In [23]:
df_superp = df[df['subs'] > 300000]
df_superp

Empty DataFrame
Columns: [ChannelID, subs, nvideos, views, Category, Language, Type]
Index: []

#### Popular Channel

In [24]:
df_p = df[df['subs'] > 100000]
df_p

ChannelID    subs  nvideos   views Category  Language        Type
Y0001     Y0001  112407        8  137830     food   English   Goverment
Y0004     Y0004  154427       92  172224   gaming   English         NGO
Y0005     Y0005  171466       61  183685     food   English  Individual
Y0008     Y0008  142673       87  154982     food   English   Corperate
Y0013     Y0013  112532       20   74012   gaming   English   Goverment
...         ...     ...      ...     ...      ...       ...         ...
Y9993     Y9993  149002        3  140254   gaming  Japanese   Goverment
Y9994     Y9994  100716       70   90956     news  Japanese         NGO
Y9995     Y9995  119716       68    5922     food   English   Goverment
Y9996     Y9996  111044       19   58326    music    Franch  Individual
Y9998     Y9998  233726       11   78299   gaming   English         NGO

[4954 rows x 7 columns]

#### Start up channel

In [25]:
df_begin = df[df['subs'] < 100]
df_begin

ChannelID  subs  nvideos  views Category Language        Type
Y0123     Y0123     1       40      0   gaming  English  Individual
Y0189     Y0189     1       17      0    music  English  Individual
Y0198     Y0198     1       47    826     news   Russia   Goverment
Y0221     Y0221     1       45      0   travel  English         NGO
Y0248     Y0248     1       83    885   travel  English  Individual
...         ...   ...      ...    ...      ...      ...         ...
Y9769     Y9769     1       42      0   gaming  English   Goverment
Y9791     Y9791     1       64    199   travel  English  Individual
Y9864     Y9864     1       14     54    music  English   Corperate
Y9901     Y9901     1       77      0    music  English         NGO
Y9944     Y9944     1        7      0   travel  Spanish  Individual

[260 rows x 7 columns]

#### Popular English Channel

In [26]:
df_EnglishP = df[(df['subs'] > 100000) & (df['Language'] == 'English')]
df_EnglishP

ChannelID    subs  nvideos   views Category Language        Type
Y0001     Y0001  112407        8  137830     food  English   Goverment
Y0004     Y0004  154427       92  172224   gaming  English         NGO
Y0005     Y0005  171466       61  183685     food  English  Individual
Y0008     Y0008  142673       87  154982     food  English   Corperate
Y0013     Y0013  112532       20   74012   gaming  English   Goverment
...         ...     ...      ...     ...      ...      ...         ...
Y9979     Y9979  135756       35   83628   gaming  English         NGO
Y9984     Y9984  152586       41    8405   travel  English         NGO
Y9985     Y9985  115796        8  146382    music  English  Individual
Y9995     Y9995  119716       68    5922     food  English   Goverment
Y9998     Y9998  233726       11   78299   gaming  English         NGO

[2508 rows x 7 columns]

#### Gaming channel with many videos

In [56]:
df.describe()

subs       nvideos          views
count   10000.000000  10000.000000   10000.000000
mean   100101.359700     49.889900   75592.870000
std     48754.745113     28.390484   60618.858148
min         1.000000      1.000000       0.000000
25%     66152.250000     26.000000   26416.000000
50%     99925.500000     50.000000   62107.500000
75%    133144.250000     74.000000  111801.000000
max    308292.000000     99.000000  368670.000000

In [27]:
df_gaming_nv = df[(df['Category'] == 'gaming') & (df['nvideos'] > 90)]
df_gaming_nv

ChannelID    subs  nvideos   views Category Language        Type
Y0004     Y0004  154427       92  172224   gaming  English         NGO
Y0039     Y0039  114186       96  145534   gaming  English  Individual
Y0043     Y0043   83225       99    2881   gaming  English  Individual
Y0075     Y0075   54639       95   70018   gaming   Franch  Individual
Y0299     Y0299  119074       99   79042   gaming  English  Individual
...         ...     ...      ...     ...      ...      ...         ...
Y9750     Y9750  101044       96  148319   gaming  English         NGO
Y9784     Y9784  100741       91   83593   gaming   Franch  Individual
Y9793     Y9793   83465       99       0   gaming  English         NGO
Y9924     Y9924   71820       92  106613   gaming  English         NGO
Y9987     Y9987   72528       91   28345   gaming  English   Goverment

[207 rows x 7 columns]

#### Non-Corperate and News channel

In [28]:
df_nc_news = df[(df['Category'] == 'news') & (df['Type'] != 'Corperate')]
df_nc_news

ChannelID    subs  nvideos   views Category  Language        Type
Y0006     Y0006   25407       30   29163     news   English         NGO
Y0009     Y0009   42078       66   42632     news   English  Individual
Y0017     Y0017  182756       86  150412     news   English         NGO
Y0027     Y0027   87038       54   70244     news   English  Individual
Y0050     Y0050   93176       96   43607     news    Franch         NGO
...         ...     ...      ...     ...      ...       ...         ...
Y9964     Y9964   32626       86   14193     news   Spanish  Individual
Y9966     Y9966   81409       78   90670     news  Japanese  Individual
Y9969     Y9969   73792       19  105253     news   Spanish  Individual
Y9994     Y9994  100716       70   90956     news  Japanese         NGO
Y9997     Y9997   63854       66   78399     news   English  Individual

[1792 rows x 7 columns]

#### Top Subs **and** Top nvideos

In [29]:
df_subs_and_nvideos = df[(df['subs'] > 200000) & (df['nvideos'] > 90)]
df_subs_and_nvideos

ChannelID    subs  nvideos   views Category  Language        Type
Y0457     Y0457  200578       98  179438    music   English         NGO
Y1234     Y1234  270322       91  246792    music   English  Individual
Y1752     Y1752  252441       97   94488    music   Spanish         NGO
Y1966     Y1966  239748       95  234882   gaming   English   Goverment
Y2118     Y2118  203434       94  251128   gaming    Russia   Goverment
Y2264     Y2264  209237       99  214449     news   English  Individual
Y2369     Y2369  215407       91  222893   travel   English  Individual
Y2655     Y2655  216743       98  294638   gaming   Chinese         NGO
Y2788     Y2788  253750       95   41430     food    Russia  Individual
Y3241     Y3241  204562       91   36758   travel   English         NGO
Y3638     Y3638  203695       92  105152   travel   English  Individual
Y4299     Y4299  206313       92  262688     food    Franch         NGO
Y4448     Y4448  209516       99   86288   travel   Chinese  Individual
Y4864     Y4864  204706       99  196701   gaming    Franch         NGO
Y5119     Y5119  206155       97  277033     food  Japanese         NGO
Y5522     Y5522  207977       96  272143    music   English   Goverment
Y5687     Y5687  212592       94  195757    music    Franch         NGO
Y6402     Y6402  222586       98  253222     news  Japanese   Corperate
Y6499     Y6499  210285       92  239858   gaming   English  Individual
Y6777     Y6777  251861       91  243649    music    Franch  Individual
Y7162     Y7162  206708       91  221836    music   English  Individual
Y7860     Y7860  234626       92  229870   travel   English         NGO
Y8038     Y8038  200119       92   28748   travel   English   Corperate
Y8525     Y8525  244921       97  359679     food   English  Individual
Y8773     Y8773  213818       97  224340     news   English         NGO

#### Top Subs **or** Top nvideos

In [30]:
df_subs_or_nvideos = df[(df['subs'] > 200000) | (df['nvideos'] > 90)]
df_subs_or_nvideos

ChannelID    subs  nvideos   views Category Language        Type
Y0004     Y0004  154427       92  172224   gaming  English         NGO
Y0010     Y0010   94659       92   19164    music  English   Goverment
Y0018     Y0018  214402       24  213773   gaming  Chinese         NGO
Y0034     Y0034   77831       95   30652     food  English         NGO
Y0039     Y0039  114186       96  145534   gaming  English  Individual
...         ...     ...      ...     ...      ...      ...         ...
Y9955     Y9955   87258       96   52558   travel   Franch   Goverment
Y9973     Y9973  120056       98  109683     food  English         NGO
Y9977     Y9977  131093       94  186946   travel  English  Individual
Y9987     Y9987   72528       91   28345   gaming  English   Goverment
Y9998     Y9998  233726       11   78299   gaming  English         NGO

[1098 rows x 7 columns]

### Aggregation

In [58]:
byCategory = df.groupby('Category')
byCategory.sum()

ChannelID       subs  \
Category                                                                 
food      Y0005Y0008Y0015Y0025Y0031Y0032Y0034Y0042Y0050Y...  205460216   
gaming    Y0001Y0009Y0010Y0023Y0027Y0036Y0049Y0052Y0059Y...  202859921   
music     Y0002Y0006Y0017Y0019Y0020Y0029Y0035Y0037Y0046Y...  204115543   
news      Y0000Y0003Y0007Y0011Y0012Y0014Y0028Y0030Y0038Y...  193861068   
travel    Y0004Y0013Y0016Y0018Y0021Y0022Y0024Y0026Y0033Y...  194716849   

          nvideos      views  \
Category                       
food       102013  151651646   
gaming     101448  152453566   
music      100263  156411560   
news        97345  148140906   
travel      97830  147271022   

                                                   Language  \
Category                                                      
food      EnglishChineseSpanishEnglishEnglishEnglishJapa...   
gaming    EnglishEnglishEnglishSpanishEnglishRussiaEngli...   
music     EnglishChineseRussiaEnglishEnglishSpanishEngli...   
news      EnglishChineseEnglishChineseFranchEnglishEngli...   
travel    JapaneseEnglishRussiaChineseEnglishChineseEngl...   

                                                       Type  
Category                                                     
food      GovermentIndividualIndividualCorperateCorperat...  
gaming    NGOIndividualIndividualIndividualNGOIndividual...  
music     IndividualGovermentCorperateIndividualIndividu...  
news      NGOIndividualIndividualCorperateIndividualNGOI...  
travel    NGOIndividualCorperateGovermentIndividualIndiv...

In [32]:
byCategory.mean()

<ipython-input-32-4fe0643856b0>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  byCategory.mean()


subs    nvideos         views
Category                                        
food      100040.159226  49.306548  75921.875992
gaming     99108.617032  50.172311  76012.443725
music     100346.642495  50.544625  75803.384888
news       99632.784855  50.510532  75957.311936
travel     99516.782587  49.083582  74892.036816

In [33]:
byLanguage = df.groupby('Language')
byLanguage.sum()

<ipython-input-33-7ff598080e9a>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  byLanguage.sum()


subs  nvideos      views
Language                               
Chinese   104324228    53327   79330991
English   496591607   250622  376477909
Franch    101118223    49236   76222840
Japanese  106116938    51277   83271965
Russia     92832378    46971   72219624
Spanish    96287775    47765   69644309

In [34]:
byLanguage.mean()

<ipython-input-34-b9813ba23235>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  byLanguage.mean()


subs    nvideos         views
Language                                        
Chinese    99831.797129  51.030622  75914.823923
English    99697.170648  50.315599  75582.796426
Franch    101320.864729  49.334669  76375.591182
Japanese  101450.227533  49.021989  79609.909178
Russia     97308.572327  49.235849  75701.911950
Spanish    98655.507172  48.939549  71356.873975

In [59]:
df

ChannelID    subs  nvideos   views Category  Language        Type
Y0000     Y0000   25979       33   25011     news   English         NGO
Y0001     Y0001   72016       82   69990   gaming   English         NGO
Y0002     Y0002       1       16       0    music   English  Individual
Y0003     Y0003  110656       71  119443     news   Chinese  Individual
Y0004     Y0004  118882       50  168311   travel  Japanese         NGO
...         ...     ...      ...     ...      ...       ...         ...
Y9995     Y9995   57563       95    2954     news   English   Goverment
Y9996     Y9996  110231       57  164929   gaming   English  Individual
Y9997     Y9997  113216       34  129475     news   English         NGO
Y9998     Y9998   94035       24   14145   gaming    Franch   Goverment
Y9999     Y9999   47998       67   71057     food    Franch   Goverment

[10000 rows x 7 columns]

In [62]:
byLanType = df.groupby(['Language', 'Type'])
byLanType.describe()

subs                                                \
                      count           mean           std    min       25%   
Language Type                                                               
Chinese  Corperate     96.0  103177.239583  50815.153338    1.0  67824.75   
         Goverment    194.0   99805.845361  49975.837094    1.0  62683.00   
         Individual   407.0   97006.358722  48672.625840    1.0  64910.00   
         NGO          278.0  100753.561151  46599.913406    1.0  68298.25   
English  Corperate    468.0   99921.807692  47690.900781    1.0  66608.25   
         Goverment   1015.0  100942.159606  47704.934156    1.0  70158.00   
         Individual  2059.0   99820.037397  48999.043951    1.0  65336.50   
         NGO         1476.0   99086.583333  49496.031256    1.0  63904.75   
Franch   Corperate     91.0  110077.087912  51466.350646    1.0  70373.00   
         Goverment    192.0  102808.281250  51231.961246    1.0  66839.00   
         Individual   420.0  102274.990476  49505.124988    1.0  68995.75   
         NGO          313.0  100271.482428  50291.940632    1.0  63040.00   
Japanese Corperate     79.0   98020.392405  50284.779063    1.0  70566.50   
         Goverment    196.0   98175.311224  47744.209547    1.0  67123.00   
         Individual   398.0  100098.522613  45956.159441    1.0  71112.00   
         NGO          340.0  102128.814706  47887.234699    1.0  70268.50   
Russia   Corperate    117.0  100579.435897  49016.228122    1.0  70366.00   
         Goverment    180.0  101295.444444  51489.610922    1.0  63655.50   
         Individual   386.0   98252.484456  50579.861928    1.0  62478.00   
         NGO          318.0  103123.364780  48640.344360    1.0  72718.50   
Spanish  Corperate    114.0  104470.578947  44223.423578    1.0  75957.50   
         Goverment    204.0   94428.892157  45854.116524  369.0  63224.50   
         Individual   393.0   98421.725191  48078.978916    1.0  66689.00   
         NGO          266.0  101639.176692  49908.947621    1.0  67402.75   

                                                   nvideos             ...  \
                          50%        75%       max   count       mean  ...   
Language Type                                                          ...   
Chinese  Corperate   105068.0  136264.50  278884.0    96.0  52.666667  ...   
         Goverment   100387.5  133637.00  253005.0   194.0  51.391753  ...   
         Individual   94910.0  127576.00  252528.0   407.0  50.928747  ...   
         NGO         100036.0  129893.25  243559.0   278.0  50.561151  ...   
English  Corperate   101752.0  132465.25  267763.0   468.0  52.438034  ...   
         Goverment   101382.0  134502.50  266001.0  1015.0  49.444335  ...   
         Individual   99306.0  133420.00  252063.0  2059.0  50.056824  ...   
         NGO          98525.5  133332.00  266470.0  1476.0  48.594173  ...   
Franch   Corperate   107170.0  137803.50  236628.0    91.0  46.340659  ...   
         Goverment   104704.0  140462.75  227683.0   192.0  49.119792  ...   
         Individual  102223.0  136873.75  252473.0   420.0  49.645238  ...   
         NGO         102093.0  132074.00  265177.0   313.0  50.731629  ...   
Japanese Corperate    91157.0  131234.50  250290.0    79.0  53.658228  ...   
         Goverment    94151.0  132647.50  261258.0   196.0  50.270408  ...   
         Individual  101456.5  130789.50  227672.0   398.0  49.145729  ...   
         NGO         103348.0  131449.00  264837.0   340.0  50.576471  ...   
Russia   Corperate   102913.0  131795.00  225127.0   117.0  47.384615  ...   
         Goverment    96949.0  141541.00  308292.0   180.0  52.250000  ...   
         Individual   97994.5  134418.25  226223.0   386.0  47.494819  ...   
         NGO         105437.0  133058.25  233583.0   318.0  50.905660  ...   
Spanish  Corperate   105554.0  138112.25  201945.0   114.0  47.885965  ...   
         Goverment    89179.0  127909.25  205782.0   204.0  50.254902  

In [65]:
byLanType.describe()[['subs','views']]

subs                                                \
                      count           mean           std    min       25%   
Language Type                                                               
Chinese  Corperate     96.0  103177.239583  50815.153338    1.0  67824.75   
         Goverment    194.0   99805.845361  49975.837094    1.0  62683.00   
         Individual   407.0   97006.358722  48672.625840    1.0  64910.00   
         NGO          278.0  100753.561151  46599.913406    1.0  68298.25   
English  Corperate    468.0   99921.807692  47690.900781    1.0  66608.25   
         Goverment   1015.0  100942.159606  47704.934156    1.0  70158.00   
         Individual  2059.0   99820.037397  48999.043951    1.0  65336.50   
         NGO         1476.0   99086.583333  49496.031256    1.0  63904.75   
Franch   Corperate     91.0  110077.087912  51466.350646    1.0  70373.00   
         Goverment    192.0  102808.281250  51231.961246    1.0  66839.00   
         Individual   420.0  102274.990476  49505.124988    1.0  68995.75   
         NGO          313.0  100271.482428  50291.940632    1.0  63040.00   
Japanese Corperate     79.0   98020.392405  50284.779063    1.0  70566.50   
         Goverment    196.0   98175.311224  47744.209547    1.0  67123.00   
         Individual   398.0  100098.522613  45956.159441    1.0  71112.00   
         NGO          340.0  102128.814706  47887.234699    1.0  70268.50   
Russia   Corperate    117.0  100579.435897  49016.228122    1.0  70366.00   
         Goverment    180.0  101295.444444  51489.610922    1.0  63655.50   
         Individual   386.0   98252.484456  50579.861928    1.0  62478.00   
         NGO          318.0  103123.364780  48640.344360    1.0  72718.50   
Spanish  Corperate    114.0  104470.578947  44223.423578    1.0  75957.50   
         Goverment    204.0   94428.892157  45854.116524  369.0  63224.50   
         Individual   393.0   98421.725191  48078.978916    1.0  66689.00   
         NGO          266.0  101639.176692  49908.947621    1.0  67402.75   

                                                     views                \
                          50%        75%       max   count          mean   
Language Type                                                              
Chinese  Corperate   105068.0  136264.50  278884.0    96.0  75377.322917   
         Goverment   100387.5  133637.00  253005.0   194.0  73479.092784   
         Individual   94910.0  127576.00  252528.0   407.0  74515.122850   
         NGO         100036.0  129893.25  243559.0   278.0  69143.039568   
English  Corperate   101752.0  132465.25  267763.0   468.0  77530.032051   
         Goverment   101382.0  134502.50  266001.0  1015.0  75579.282759   
         Individual   99306.0  133420.00  252063.0  2059.0  75259.672171   
         NGO          98525.5  133332.00  266470.0  1476.0  74598.260163   
Franch   Corperate   107170.0  137803.50  236628.0    91.0  84979.648352   
         Goverment   104704.0  140462.75  227683.0   192.0  76320.984375   
         Individual  102223.0  136873.75  252473.0   420.0  76818.900000   
         NGO         102093.0  132074.00  265177.0   313.0  77157.277955   
Japanese Corperate    91157.0  131234.50  250290.0    79.0  69084.075949   
         Goverment    94151.0  132647.50  261258.0   196.0  79013.617347   
         Individual  101456.5  130789.50  227672.0   398.0  78271.489950   
         NGO         103348.0  131449.00  264837.0   340.0  76537.235294   
Russia   Corperate   102913.0  131795.00  225127.0   117.0  79344.461538   
         Goverment    96949.0  141541.00  308292.0   180.0  80472.161111   
         Individual   97994.5  134418.25  226223.0   386.0  79084.103627   
         NGO         105437.0  133058.25  233583.0   318.0  76350.940252   
Spanish  Corperate   105554.0  138112.25  201945.0   114.0  69673.973684   
         Goverment    89179.0  127909.25  205782.0   204.0  70591.225490   
         Individual   98098.0  129777.00  2

In [70]:
byLanType.describe().loc['English'][["subs", "views"]]

subs                                                        \
             count           mean           std  min       25%       50%   
Type                                                                       
Corperate    468.0   99921.807692  47690.900781  1.0  66608.25  101752.0   
Goverment   1015.0  100942.159606  47704.934156  1.0  70158.00  101382.0   
Individual  2059.0   99820.037397  48999.043951  1.0  65336.50   99306.0   
NGO         1476.0   99086.583333  49496.031256  1.0  63904.75   98525.5   

                                  views                                   \
                  75%       max   count          mean           std  min   
Type                                                                       
Corperate   132465.25  267763.0   468.0  77530.032051  61227.473771  0.0   
Goverment   134502.50  266001.0  1015.0  75579.282759  58775.997705  0.0   
Individual  133420.00  252063.0  2059.0  75259.672171  59913.142356  0.0   
NGO         133332.00  266470.0  1476.0  74598.260163  59964.167190  0.0   

                                                    
                 25%      50%        75%       max  
Type                                                
Corperate   28336.75  66158.5  116774.50  300083.0  
Goverment   28565.50  63423.0  106626.00  348203.0  
Individual  26432.50  62250.0  112107.50  292298.0  
NGO         25198.25  60304.5  110852.25  346134.0

### Manipulation

In [71]:
df['subpervideo'] = df['subs']/df['nvideos']
df['subpervideo'].describe()

count     10000.000000
mean       5246.278684
std       13552.789290
min           0.010101
25%        1181.246269
50%        1994.541727
75%        3891.252364
max      210566.000000
Name: subpervideo, dtype: float64

In [75]:
df

ChannelID    subs  nvideos   views Category  Language        Type  \
Y0000     Y0000   25979       33   25011     news   English         NGO   
Y0001     Y0001   72016       82   69990   gaming   English         NGO   
Y0002     Y0002       1       16       0    music   English  Individual   
Y0003     Y0003  110656       71  119443     news   Chinese  Individual   
Y0004     Y0004  118882       50  168311   travel  Japanese         NGO   
...         ...     ...      ...     ...      ...       ...         ...   
Y9995     Y9995   57563       95    2954     news   English   Goverment   
Y9996     Y9996  110231       57  164929   gaming   English  Individual   
Y9997     Y9997  113216       34  129475     news   English         NGO   
Y9998     Y9998   94035       24   14145   gaming    Franch   Goverment   
Y9999     Y9999   47998       67   71057     food    Franch   Goverment   

       subpervideo  
Y0000   787.242424  
Y0001   878.243902  
Y0002     0.062500  
Y0003  1558.535211  
Y0004  2377.640000  
...            ...  
Y9995   605.926316  
Y9996  1933.877193  
Y9997  3329.882353  
Y9998  3918.125000  
Y9999   716.388060  

[10000 rows x 8 columns]

In [77]:
df['viewspervideo'] = df['views']/df['nvideos']
df['viewspervideo'].describe()

count     10000.000000
mean       3979.950248
std       12028.857071
min           0.000000
25%         550.666038
50%        1366.424038
75%        2985.054668
max      299405.000000
Name: viewspervideo, dtype: float64

In [78]:
df['viewspersub'] = df['views']/df['subs']
df['viewspersub'].describe()

count    10000.000000
mean         7.052247
std         65.454379
min          0.000000
25%          0.375176
50%          0.759071
75%          1.137625
max       1033.000000
Name: viewspersub, dtype: float64

In [41]:
df.head(10)

ChannelID    subs  nvideos   views Category Language        Type  \
Y0000     Y0000   28045       61   34515     food   Russia  Individual   
Y0001     Y0001  112407        8  137830     food  English   Goverment   
Y0002     Y0002   75610       89   75561     food   Franch   Goverment   
Y0003     Y0003   68566       17   14567     food  English  Individual   
Y0004     Y0004  154427       92  172224   gaming  English         NGO   
Y0005     Y0005  171466       61  183685     food  English  Individual   
Y0006     Y0006   25407       30   29163     news  English         NGO   
Y0007     Y0007   90808       74  133107     food   Franch   Goverment   
Y0008     Y0008  142673       87  154982     food  English   Corperate   
Y0009     Y0009   42078       66   42632     news  English  Individual   

        subpervideo  viewspervideo  viewspersub  
Y0000    459.754098     565.819672     1.230701  
Y0001  14050.875000   17228.750000     1.226169  
Y0002    849.550562     849.000000     0.999352  
Y0003   4033.294118     856.882353     0.212452  
Y0004   1678.554348    1872.000000     1.115245  
Y0005   2810.918033    3011.229508     1.071262  
Y0006    846.900000     972.100000     1.147833  
Y0007   1227.135135    1798.743243     1.465807  
Y0008   1639.919540    1781.402299     1.086274  
Y0009    637.545455     645.939394     1.013166

In [79]:
df.tail(10)

ChannelID    subs  nvideos   views Category  Language        Type  \
Y9990     Y9990  175950       44   45187   travel   Spanish         NGO   
Y9991     Y9991   14810       92    4594     food   English  Individual   
Y9992     Y9992    6707       31    1000    music  Japanese  Individual   
Y9993     Y9993  154503       93   12315     news  Japanese         NGO   
Y9994     Y9994   81904       46   12580     news   English         NGO   
Y9995     Y9995   57563       95    2954     news   English   Goverment   
Y9996     Y9996  110231       57  164929   gaming   English  Individual   
Y9997     Y9997  113216       34  129475     news   English         NGO   
Y9998     Y9998   94035       24   14145   gaming    Franch   Goverment   
Y9999     Y9999   47998       67   71057     food    Franch   Goverment   

       subpervideo  viewspervideo  viewspersub  
Y9990  3998.863636    1026.977273     0.256817  
Y9991   160.978261      49.934783     0.310196  
Y9992   216.354839      32.258065     0.149098  
Y9993  1661.322581     132.419355     0.079707  
Y9994  1780.521739     273.478261     0.153594  
Y9995   605.926316      31.094737     0.051318  
Y9996  1933.877193    2893.491228     1.496212  
Y9997  3329.882353    3808.088235     1.143610  
Y9998  3918.125000     589.375000     0.150423  
Y9999   716.388060    1060.552239     1.480416

## Congratulations! You completed our course: Data Wrangling -- Fundamentals