In [3]:
import numpy as np

In [12]:
mda = np.array([[1,2,3], [4,5,6], [7,8,9]])
mda

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
mda[0]

array([1, 2, 3])

In [15]:
mda[1][1]

5

In [16]:
mda[:, 1]

array([2, 5, 8])

In [17]:
mda[0:2, 2]

array([3, 6])

In [18]:
np.size(mda)

9

In [19]:
len(mda)

3

In [20]:
np.size(mda, 0)

3

In [21]:
np.size(mda, 1)

3

In [22]:
np.shape(mda)

(3, 3)

In [23]:
len(mda[0])

3

In [30]:
ar = np.random.randint(0, 10, (5, 7))
ar

array([[5, 9, 4, 6, 7, 1, 7],
       [3, 4, 5, 1, 7, 1, 6],
       [5, 4, 9, 7, 3, 4, 7],
       [2, 7, 1, 0, 0, 6, 9],
       [4, 5, 6, 4, 1, 1, 3]])

In [31]:
np.shape(ar)

(5, 7)

In [32]:
mda

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
type(mda[0])

numpy.ndarray

In [34]:
mda[2][1]

8

In [35]:
mda[2,1]

8

In [39]:
mda[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
mda[:, 1]

array([2, 5, 8])

In [41]:
mda[:][1]

array([4, 5, 6])

In [48]:
mda[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [49]:
mda[:, 1]

array([2, 5, 8])

In [62]:
mda[:1, -2:] += 3

In [63]:
mda

array([[ 1,  5,  6],
       [ 4,  8,  9],
       [ 7, 11, 12]])

In [64]:
VEC = [1,2,3]

In [65]:
mda + VEC

array([[ 2,  7,  9],
       [ 5, 10, 12],
       [ 8, 13, 15]])

In [66]:
ar1 = np.zeros(shape = (6,3), dtype = int)
ar1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [70]:
np.reshape(ar1, (-1, 2))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [76]:
ar2 = np.linspace(0, 10, 45)
ar2

array([ 0.        ,  0.22727273,  0.45454545,  0.68181818,  0.90909091,
        1.13636364,  1.36363636,  1.59090909,  1.81818182,  2.04545455,
        2.27272727,  2.5       ,  2.72727273,  2.95454545,  3.18181818,
        3.40909091,  3.63636364,  3.86363636,  4.09090909,  4.31818182,
        4.54545455,  4.77272727,  5.        ,  5.22727273,  5.45454545,
        5.68181818,  5.90909091,  6.13636364,  6.36363636,  6.59090909,
        6.81818182,  7.04545455,  7.27272727,  7.5       ,  7.72727273,
        7.95454545,  8.18181818,  8.40909091,  8.63636364,  8.86363636,
        9.09090909,  9.31818182,  9.54545455,  9.77272727, 10.        ])

In [79]:
ar1 = np.arange(1,7).reshape(2,3)
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
ar2 = np.arange(3,9).reshape(2,3)
ar2 

array([[3, 4, 5],
       [6, 7, 8]])

In [81]:
ar1 + ar2

array([[ 4,  6,  8],
       [10, 12, 14]])

In [82]:
ar1 * ar2

array([[ 3,  8, 15],
       [24, 35, 48]])

In [83]:
ar1 ** ar2

array([[      1,      16,     243],
       [   4096,   78125, 1679616]])

In [84]:
ar1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
ar1.T@ar2

array([[27, 32, 37],
       [36, 43, 50],
       [45, 54, 63]])

In [93]:
ar3 = np.arange(5)
ar4 = np.arange(5)
ar3, ar4


(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))