In [1]:
import numpy as np

In [10]:
ar = np.random.randint(0, 100, (10))
ar

array([ 9, 65, 33, 79, 75, 77, 71, 63,  7, 68])

In [3]:
odd_mask = ar % 2 == 1
odd_mask

array([ True, False,  True,  True, False,  True, False, False,  True,
       False])

In [4]:
ar[odd_mask]

array([59, 79, 83,  1, 77])

In [5]:
ar[ar % 2 == 1]

array([59, 79, 83,  1, 77])

In [6]:
ar[ar % 2 == 0]

array([88, 88, 60, 18, 82])

In [11]:
ar1 = np.random.randint(0, 100, (4,4))
ar2 = np.random.randint(0, 100, (4,4))

In [12]:
ar1, ar2

(array([[69, 97, 62, 81],
        [26, 16, 13, 34],
        [48, 81, 84, 73],
        [22, 89, 28, 91]]),
 array([[95, 15, 22, 42],
        [23, 30, 66, 86],
        [ 8, 76, 86, 35],
        [24, 63, 32, 31]]))

In [13]:
ar1[ar1 < ar2]

array([69, 16, 13, 34, 84, 22, 28])

In [14]:
ar2[ar1 < ar2]

array([95, 30, 66, 86, 86, 24, 32])

In [15]:
ar1[ar1 + ar2 > 100]

array([69, 97, 81, 34, 81, 84, 73, 89, 91])

In [16]:
ar1 + ar2

array([[164, 112,  84, 123],
       [ 49,  46,  79, 120],
       [ 56, 157, 170, 108],
       [ 46, 152,  60, 122]])

In [17]:
ar2[ar1 + ar2 > 100]

array([95, 15, 42, 86, 76, 86, 35, 63, 31])