In [21]:
import time
import numpy as np

In [14]:
list1 = [x**2 for x in range(10)]
array1 = np.arange(10) ** 2

In [30]:
i = time.time()
for i in range(0,100000000):
    list1[5]
f = time.time()
print(f-i)

1601009282.684267


In [31]:
i = time.time()
for i in range(0,100000000):
    array1[5]
f = time.time()
print(f-i)

1601009288.035831


In [33]:
array1 = np.array(list1)
print(type(array1))

<class 'numpy.ndarray'>


In [52]:
array2 = np.arange(1,10,dtype = int)
print(array2)

[1 2 3 4 5 6 7 8 9]


In [50]:
array2

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
array2_size = np.size(array2)
array2_dim = array2.ndim
array2_type = type(array2)
array2_elements_type = array2.dtype

print(array2_size)
print(array2_dim)
print(array2_type)
print(array2_elements_type)

9
1
<class 'numpy.ndarray'>
int64


In [54]:
array3 = np.array(list1)
array3

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [55]:
list1

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [57]:
list1 * 2

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [61]:
array3 + array3 

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [62]:
array3 * list1

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [63]:
array3 + 1

array([ 1,  2,  5, 10, 17, 26, 37, 50, 65, 82])

In [ ]:
#ELEMENT WISE OPERATIONS

In [64]:
array1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [68]:
array2 = np.arange(0,10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
array1 * array2

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [70]:
np.multiply(array1, array2)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [71]:
np.sum(np.multiply(array1, array2))

2025

In [72]:
array1.dot(array2)

2025

In [73]:
array1@array2

2025

In [74]:
array1


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [75]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
array2 = np.arange(0,10,dtype=float)

In [77]:
array2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
array1 + array2

array([ 0.,  2.,  6., 12., 20., 30., 42., 56., 72., 90.])

In [81]:
np.add(array1, array2) == array1 + array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [82]:
np.negative(array1)

array([  0,  -1,  -4,  -9, -16, -25, -36, -49, -64, -81])

In [87]:
array1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [86]:
array2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
np.hypot(array1, array2)

array([ 0.        ,  1.41421356,  4.47213595,  9.48683298, 16.4924225 ,
       25.49509757, 36.49657518, 49.49747468, 64.49806199, 81.49846624])

In [90]:
np.greater(array2, array1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [91]:
array2 = np.arange(0,11, 1.5)
array2

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5])

In [92]:
np.ceil(array2)

array([ 0.,  2.,  3.,  5.,  6.,  8.,  9., 11.])

In [93]:
np.floor(array2)

array([ 0.,  1.,  3.,  4.,  6.,  7.,  9., 10.])

In [95]:
np.greater(np.ceil(array2), np.floor(array2))

array([False,  True, False,  True, False,  True, False,  True])

In [101]:
#RANDOM EMBBEDED IN NUMBER PY - NUMPY
ar = np.random.randint(0,10, (10))
ar

array([7, 6, 0, 8, 9, 0, 1, 2, 1, 6])

In [102]:
ar.sum()

40

In [103]:
ar.mean()

4.0

In [104]:
ar.std()

3.3466401061363023

In [105]:
ar.var()

11.2

In [106]:
ar.max()

9

In [107]:
ar.min()

0